name: test
on: pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [1.11, 1.12, 1.13, 1.14]
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goversion }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v ./...
      - name: Run tests
        run: go test -v -race ./...
